### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andbue** [Planet-AI-GmbH/tf2_aip_base#12]
Since @ChWick relocated many critical parts of calamari into the tfaip-framework, we rely heavily on its functionality. Unfortunately, there are some issues (https://github.com/Calamari-OCR/calamari/issues/3) with the GPL license further down the line of dependencies (https://github.com/Calamari-OCR/calamari/issues/3#issuecomment-1434581426). Would it be possible to put tfaip under a more permissive LGPL license? This would allow us to import and use the library as a dependency via setup.py without having to license our code under the (L)GPL as well.

**Comment by mikegerber** [comment]
Subscribing, as we are also transitively affected with https://github.com/OCR-D/ocrd_calamari/issues/84 (also Apache-licensed).

**Comment by bertsky** [comment]
Alternatively, you might consider adding an exemption specifically for Calamari (allowing a different sub-license for that use-case alone).

**Comment by amitdo** [comment]
>Alternatively, you might consider adding an exemption specifically for Calamari (allowing a different sub-license for that use-case alone). 

IMO, this is a terrible idea. 

Do you have examples to popular projects that use this kind of practice?

**Comment by kba** [comment]
> > Alternatively, you might consider adding an exemption specifically for Calamari (allowing a different sub-license for that use-case alone).
> 
> IMO, this is a terrible idea.

It's not the best solution but as a license holder, you can always waive it for a specific project. It's unusual for Open Source though and probably only pushes the issue further downstream.

> Do you have examples to popular projects that use this kind of practice?

https://spdx.github.io/license-list-data/exceptions-index.html

**Comment by amitdo** [comment]
https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines

**Comment by amitdo** [comment]
>https://spdx.github.io/license-list-data/exceptions-index.html

This is a list of licences with exception clause. Is one of them has exception for specific product?

**Comment by mikegerber** [comment]
A rather small further complication: This uses (among other dependencies I haven't checked) python-Levenshtein, which is GPL. So this must be GPL as well. The good news is that it's just one line in the examples and could be easily replaced by using rapidfuzz. 

Other dependencies must be checked as well.

**Comment by stweil** [comment]
In addition, all contributors must agree to a license change. Luckily this seems to be a small number here.

**Comment by stweil** [comment]
`python-Levenshtein` is the only dependency which enforces GPLv2+.

**Comment by kba** [comment]
Ping :-) It would be great if we could clear this up, because tfaip's licensing is transitively preventing us from upgrading [ocrd_calamari](https://github.com/OCR-D/ocrd_calamari/issues/84) to the 2.x version of [calamari](https://github.com/Calamari-OCR/calamari/issues/3).

@ChWick any ideas how we could resolve this?

**Comment by TobiasGruening** [comment]
We have discussed internally how we will continue to deal with the repository. The decision for this license was a conscious one and we will not change anything.

Since the hopes we had for the release of the repo have not been fulfilled, we will freeze it at its current state, archive it and no longer maintain it in the open source variant.

I'm sorry if this leads to problems, but we have to direct our resources a little differently.
